import 'package:flutter/foundation.dart';
import '../models/user.dart';

class UserService extends ChangeNotifier {
  final List<User> _users = [
    User(
      id: 1,
      username: 'preeti',
      email: 'student1@university.ac.th',
      firstName: 'ปรีติ',
      lastName: 'วงษ์สุข',
      role: UserRole.student,
      studentId: '47317',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fstudent_preeti.jpg?alt=media',
    ),
    User(
      id: 2,
      username: 'teacher1',
      email: 'teacher1@university.ac.th',
      firstName: 'อาจารย์สมหญิง',
      lastName: 'ใจงาม',
      role: UserRole.teacher,
      teacherId: 'TEA001',
      department: 'วิทยาการคอมพิวเตอร์',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_somying.jpg?alt=media',
    ),
    User(
      id: 3,
      username: 'admin1',
      email: 'admin1@university.ac.th',
      firstName: 'ผู้ดูแลระบบ',
      lastName: 'หลัก',
      role: UserRole.admin,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fadmin_profile.jpg?alt=media',
    ),
    User(
      id: 4,
      username: 'pakorn',
      email: 'admin1@university.ac.th',
      firstName: 'ปกรณ์',
      lastName: 'ไตรโชคกุล',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_pakorn.jpg?alt=media',
    ),
    User(
      id: 5,
      username: 'sathorn',
      email: 'sathorn@university.ac.th',
      firstName: 'ศาทร',
      lastName: 'ว่องดี',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_sathorn.jpg?alt=media',
    ),
    User(
      id: 6,
      username: 'patmaporn',
      email: 'patmaporn@university.ac.th',
      firstName: 'ปัทมาพร',
      lastName: 'พันธุ์ชัย',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 89)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_patmaporn.jpg?alt=media',
    ),
    User(
      id: 7,
      username: 'wansao',
      email: 'wansar@university.ac.th',
      firstName: 'วันเสาร์',
      lastName: 'ส่งศิริ',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 88)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_wansao.jpg?alt=media',
    ),
    User(
      id: 8,
      username: 'yupa',
      email: 'yupa@university.ac.th',
      firstName: 'ยุพา',
      lastName: 'ปลีผลา',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 87)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_yupa.jpg?alt=media',
    ),
    User(
      id: 9,
      username: 'apinya',
      email: 'apin@university.ac.th',
      firstName: 'อภิญญา',
      lastName: 'เชื้อปาน',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 86)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_apinya.jpg?alt=media',
    ),
    User(
      id: 10,
      username: 'nipakorn',
      email: 'nipakorn@university.ac.th',
      firstName: 'นิภากรณ์',
      lastName: 'เกิดอ้น',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 85)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_nipakorn.jpg?alt=media',
    ),
    User(
      id: 11,
      username: 'santirach',
      email: 'santirach@university.ac.th',
      firstName: 'สันติราช',
      lastName: 'จอมใจ',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 84)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_santirach.jpg?alt=media',
    ),
    User(
      id: 12,
      username: 'sutthima',
      email: 'sutthima@university.ac.th',
      firstName: 'สุทธิมา',
      lastName: 'สร้อยสิงห์',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 83)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_sutthima.jpg?alt=media',
    ),
    User(
      id: 13,
      username: 'pitchaya',
      email: 'pitchaya@university.ac.th',
      firstName: 'พิชญา',
      lastName: 'สัตยาทร',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 82)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_pitchaya.jpg?alt=media',
    ),
    User(
      id: 14,
      username: 'anongrat',
      email: 'anongrat@university.ac.th',
      firstName: 'อนงค์รัตน์',
      lastName: 'แก้วบำรุง',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 81)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_anongrat.jpg?alt=media',
    ),
    User(
      id: 15,
      username: 'attapon',
      email: 'attapon@university.ac.th',
      firstName: 'อรรถพล',
      lastName: 'พลอยมีค่า',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 80)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_attapon.jpg?alt=media',
    ),
    User(
      id: 16,
      username: 'phaitoon',
      email: 'phaitoon@university.ac.th',
      firstName: 'ไพทูรย์',
      lastName: 'กุมภาพันธ์',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 79)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_phaitoon.jpg?alt=media',
    ),
    User(
      id: 17,
      username: 'theerwara',
      email: 'theerwara@university.ac.th',
      firstName: 'ธีร์วรา',
      lastName: 'ชื่นธีรพงศ์',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 78)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_theerwara.jpg?alt=media',
    ),
    User(
      id: 18,
      username: 'chantima',
      email: 'chantima@university.ac.th',
      firstName: 'จันทิมา',
      lastName: 'ศาสตร์กลาง',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 77)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_chantima.jpg?alt=media',
    ),
    User(
      id: 19,
      username: 'pailin',
      email: 'pailin@university.ac.th',
      firstName: 'ไพลิน',
      lastName: 'จอมใจ',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 76)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_pailin.jpg?alt=media',
    ),
    User(
      id: 20,
      username: 'kantinan',
      email: 'kantinan@university.ac.th',
      firstName: 'กันตินันท์',
      lastName: 'ยอดบุญเรือง',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 75)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_kantinan.jpg?alt=media',
    ),
    User(
      id: 21,
      username: 'narawadee',
      email: 'narawadee@university.ac.th',
      firstName: 'นราวดี',
      lastName: 'เกตุน้ำเที่ยง',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 74)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_narawadee.jpg?alt=media',
    ),
    User(
      id: 22,
      username: 'petchrat',
      email: 'petchrat@university.ac.th',
      firstName: 'เพชรัตน์',
      lastName: 'คงคล้าย',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 73)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_petchrat.jpg?alt=media',
    ),
    User(
      id: 23,
      username: 'sudarat',
      email: 'sudarat@university.ac.th',
      firstName: 'สุดารัตน์',
      lastName: 'กิติจันทโรภาส',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 72)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_sudarat.jpg?alt=media',
    ),
    User(
      id: 24,
      username: 'pannawit',
      email: 'pannawit@university.ac.th',
      firstName: 'ปัณณวิชญ์',
      lastName: 'ศรีภณาภิรักษ์กุล',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 71)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_pannawit.jpg?alt=media',
    ),
    User(
      id: 25,
      username: 'phatsaya',
      email: 'phatsaya@university.ac.th',
      firstName: 'ภัทร์ศยา',
      lastName: 'จันทราวุฒิกร',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 70)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_phatsaya.jpg?alt=media',
    ),
    User(
      id: 26,
      username: 'palakorn',
      email: 'palakorn@university.ac.th',
      firstName: 'พลากร',
      lastName: 'จันทร์บูรณ์',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 69)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_palakorn.jpg?alt=media',
    ),
    User(
      id: 27,
      username: 'phumtawan',
      email: 'phumtawan@university.ac.th',
      firstName: 'ภูมิตะวัน',
      lastName: 'แสงสุข',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 68)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_phumtawan.jpg?alt=media',
    ),
    User(
      id: 28,
      username: 'kritkamol',
      email: 'kritkamol@university.ac.th',
      firstName: 'กฤชกมล',
      lastName: 'ปิตานุพงศ์',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 67)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_kritkamol.jpg?alt=media',
    ),
    User(
      id: 29,
      username: 'sirirat',
      email: 'sirirat@university.ac.th',
      firstName: 'ศิริรัตน์',
      lastName: 'สุขสบาย',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 66)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_sirirat.jpg?alt=media',
    ),
    User(
      id: 30,
      username: 'thanyarath',
      email: 'thanyarath@university.ac.th',
      firstName: 'ธัญญารัตน์',
      lastName: 'บุรวงค์',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 65)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_thanyarath.jpg?alt=media',
    ),
    User(
      id: 31,
      username: 'phanupong',
      email: 'phanupong@university.ac.th',
      firstName: 'ภานุพงศ์',
      lastName: 'บุพโกสุม',
      role: UserRole.teacher,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 64)),
      updatedAt: DateTime.now(),
      profileImageUrl:
          'https://firebasestorage.googleapis.com/v0/b/your-project.appspot.com/o/profile_images%2Fteacher_phanupong.jpg?alt=media',
    ),
  ];

  Future<User?> getUserById(int id) async {
    await Future.delayed(const Duration(milliseconds: 100));
    return _users.firstWhere((user) => user.id == id);
  }

  Future<List<User>> getAllUsers() async {
    await Future.delayed(const Duration(milliseconds: 100));
    return _users;
  }
}
